package com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage;

/**
* com/bbn/openmap/corba/CSpecialist/U2525SymbolPackage/settableFieldsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/


// rotate 2525 0.0 -> 180.0 degrees
public final class settableFieldsHolder implements org.omg.CORBA.portable.Streamable
{
  public com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields value = null;

  public settableFieldsHolder ()
  {
  }

  public settableFieldsHolder (com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFieldsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFieldsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFieldsHelper.type ();
  }

}
