package com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage;


/**
* com/bbn/openmap/corba/CSpecialist/U2525SymbolPackage/settableFieldsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/


// rotate 2525 0.0 -> 180.0 degrees
abstract public class settableFieldsHelper
{
  private static String  _id = "IDL:CSpecialist/U2525Symbol/settableFields:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFieldsHelper.id (), "settableFields", new String[] { "U2525F_p1", "U2525F_ll1", "U2525F_symbol", "U2525F_confirmed", "U2525F_reduced", "U2525F_movement", "U2525F_left2", "U2525F_left4", "U2525F_right2", "U2525F_right3", "U2525F_right4", "U2525F_bottom1", "U2525F_nom_size", "U2525F_min_size", "U2525F_max_size", "U2525F_scale", "U2525F_is_hq", "U2525F_rotate"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.settableFields value)
  {
    ostream.write_long (value.value ());
  }

}
