package com.bbn.openmap.corba.CSpecialist.CColorPackage;


/**
* com/bbn/openmap/corba/CSpecialist/CColorPackage/EColor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class EColor implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.CColor color = null;
  public short red = (short)0;
  public short green = (short)0;
  public short blue = (short)0;

  public EColor ()
  {
  } // ctor

  public EColor (com.bbn.openmap.corba.CSpecialist.CColor _color, short _red, short _green, short _blue)
  {
    color = _color;
    red = _red;
    green = _green;
    blue = _blue;
  } // ctor

} // class EColor
