package com.bbn.openmap.corba.CSpecialist.ForceArrowPackage;

/**
* com/bbn/openmap/corba/CSpecialist/ForceArrowPackage/EForceArrowHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class EForceArrowHolder implements org.omg.CORBA.portable.Streamable
{
  public com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrow value = null;

  public EForceArrowHolder ()
  {
  }

  public EForceArrowHolder (com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrow initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.type ();
  }

}
