package com.bbn.openmap.corba.CSpecialist.TextPackage;


/**
* com/bbn/openmap/corba/CSpecialist/TextPackage/EText.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class EText implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic egraphic = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 = null;
  public String data = null;
  public String font = null;
  public short justify = (short)0;

  public EText ()
  {
  } // ctor

  public EText (com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic _egraphic, com.bbn.openmap.corba.CSpecialist.XYPoint _p1, com.bbn.openmap.corba.CSpecialist.LLPoint _ll1, String _data, String _font, short _justify)
  {
    egraphic = _egraphic;
    p1 = _p1;
    ll1 = _ll1;
    data = _data;
    font = _font;
    justify = _justify;
  } // ctor

} // class EText
