package com.bbn.openmap.corba.CSpecialist.TextPackage;

/**
* com/bbn/openmap/corba/CSpecialist/TextPackage/ETextHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class ETextHolder implements org.omg.CORBA.portable.Streamable
{
  public com.bbn.openmap.corba.CSpecialist.TextPackage.EText value = null;

  public ETextHolder ()
  {
  }

  public ETextHolder (com.bbn.openmap.corba.CSpecialist.TextPackage.EText initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.type ();
  }

}
