package com.bbn.openmap.corba.CSpecialist.RasterPackage;


/**
* com/bbn/openmap/corba/CSpecialist/RasterPackage/ERaster.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class ERaster implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic egraphic = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 = null;
  public byte pixels[] = null;
  public short width = (short)0;
  public short height = (short)0;
  public short x_hot = (short)0;
  public short y_hot = (short)0;
  public short colorsTotal = (short)0;
  public com.bbn.openmap.corba.CSpecialist.CTEntry ct[] = null;
  public short transparent = (short)0;

  public ERaster ()
  {
  } // ctor

  public ERaster (com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic _egraphic, com.bbn.openmap.corba.CSpecialist.XYPoint _p1, com.bbn.openmap.corba.CSpecialist.LLPoint _ll1, byte[] _pixels, short _width, short _height, short _x_hot, short _y_hot, short _colorsTotal, com.bbn.openmap.corba.CSpecialist.CTEntry[] _ct, short _transparent)
  {
    egraphic = _egraphic;
    p1 = _p1;
    ll1 = _ll1;
    pixels = _pixels;
    width = _width;
    height = _height;
    x_hot = _x_hot;
    y_hot = _y_hot;
    colorsTotal = _colorsTotal;
    ct = _ct;
    transparent = _transparent;
  } // ctor

} // class ERaster
