package com.bbn.openmap.corba.CSpecialist.RectanglePackage;


/**
* com/bbn/openmap/corba/CSpecialist/RectanglePackage/ERectangle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class ERectangle implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic egraphic = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p2 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll2 = null;

  public ERectangle ()
  {
  } // ctor

  public ERectangle (com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic _egraphic, com.bbn.openmap.corba.CSpecialist.XYPoint _p1, com.bbn.openmap.corba.CSpecialist.XYPoint _p2, com.bbn.openmap.corba.CSpecialist.LLPoint _ll1, com.bbn.openmap.corba.CSpecialist.LLPoint _ll2)
  {
    egraphic = _egraphic;
    p1 = _p1;
    p2 = _p2;
    ll1 = _ll1;
    ll2 = _ll2;
  } // ctor

} // class ERectangle
