package com.bbn.openmap.corba.CSpecialist.RectanglePackage;


/**
* com/bbn/openmap/corba/CSpecialist/RectanglePackage/ERectangleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

abstract public class ERectangleHelper
{
  private static String  _id = "IDL:CSpecialist/Rectangle/ERectangle:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphicHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "egraphic",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "p1",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "p2",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "ll1",
            _tcOf_members0,
            null);
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "ll2",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangleHelper.id (), "ERectangle", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle read (org.omg.CORBA.portable.InputStream istream)
  {
    com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle value = new com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle ();
    value.egraphic = com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphicHelper.read (istream);
    value.p1 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.read (istream);
    value.p2 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.read (istream);
    value.ll1 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.read (istream);
    value.ll2 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle value)
  {
    com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphicHelper.write (ostream, value.egraphic);
    com.bbn.openmap.corba.CSpecialist.XYPointHelper.write (ostream, value.p1);
    com.bbn.openmap.corba.CSpecialist.XYPointHelper.write (ostream, value.p2);
    com.bbn.openmap.corba.CSpecialist.LLPointHelper.write (ostream, value.ll1);
    com.bbn.openmap.corba.CSpecialist.LLPointHelper.write (ostream, value.ll2);
  }

}
