package com.bbn.openmap.corba.CSpecialist.RectanglePackage;


/**
* com/bbn/openmap/corba/CSpecialist/RectanglePackage/RF_update.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class RF_update implements org.omg.CORBA.portable.IDLEntity
{
  private com.bbn.openmap.corba.CSpecialist.XYPoint ___p1;
  private com.bbn.openmap.corba.CSpecialist.XYPoint ___p2;
  private com.bbn.openmap.corba.CSpecialist.LLPoint ___ll1;
  private com.bbn.openmap.corba.CSpecialist.LLPoint ___ll2;
  private com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields __discriminator;
  private boolean __uninitialized = true;

  public RF_update ()
  {
  }

  public com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyp1 (__discriminator);
    return ___p1;
  }

  public void p1 (com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_p1;
    ___p1 = value;
    __uninitialized = false;
  }

  public void p1 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    verifyp1 (discriminator);
    __discriminator = discriminator;
    ___p1 = value;
    __uninitialized = false;
  }

  private void verifyp1 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_p1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.XYPoint p2 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyp2 (__discriminator);
    return ___p2;
  }

  public void p2 (com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_p2;
    ___p2 = value;
    __uninitialized = false;
  }

  public void p2 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    verifyp2 (discriminator);
    __discriminator = discriminator;
    ___p2 = value;
    __uninitialized = false;
  }

  private void verifyp2 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_p2)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyll1 (__discriminator);
    return ___ll1;
  }

  public void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_ll1;
    ___ll1 = value;
    __uninitialized = false;
  }

  public void ll1 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    verifyll1 (discriminator);
    __discriminator = discriminator;
    ___ll1 = value;
    __uninitialized = false;
  }

  private void verifyll1 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_ll1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.LLPoint ll2 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyll2 (__discriminator);
    return ___ll2;
  }

  public void ll2 (com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_ll2;
    ___ll2 = value;
    __uninitialized = false;
  }

  public void ll2 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    verifyll2 (discriminator);
    __discriminator = discriminator;
    ___ll2 = value;
    __uninitialized = false;
  }

  private void verifyll2 (com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.RectanglePackage.settableFields.RF_ll2)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class RF_update
