package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/_GraphicChangeStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/


// ----------------------------------------------------------------------
public class _GraphicChangeStub extends org.omg.CORBA.portable.ObjectImpl implements com.bbn.openmap.corba.CSpecialist.GraphicChange
{


  //gives the mattserver a list of graphics that it needs to refetch
  public void ChangeNotify (boolean forceRedraw, String[] gIDseq)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ChangeNotify", false);
                $out.write_boolean (forceRedraw);
                com.bbn.openmap.corba.CSpecialist.stringsHelper.write ($out, gIDseq);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ChangeNotify (forceRedraw, gIDseq        );
            } finally {
                _releaseReply ($in);
            }
  } // ChangeNotify


  //when it redraws, to do a new fillrectangle call)
  public void ForgetAll (boolean forceRedraw)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ForgetAll", false);
                $out.write_boolean (forceRedraw);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ForgetAll (forceRedraw        );
            } finally {
                _releaseReply ($in);
            }
  } // ForgetAll


  //changes the ordering of graphics
  public void RaiseGraphic (boolean forceRedraw, String[] gIDseq)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("RaiseGraphic", false);
                $out.write_boolean (forceRedraw);
                com.bbn.openmap.corba.CSpecialist.stringsHelper.write ($out, gIDseq);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                RaiseGraphic (forceRedraw, gIDseq        );
            } finally {
                _releaseReply ($in);
            }
  } // RaiseGraphic

  public void LowerGraphic (boolean forceRedraw, String[] gIDseq)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("LowerGraphic", false);
                $out.write_boolean (forceRedraw);
                com.bbn.openmap.corba.CSpecialist.stringsHelper.write ($out, gIDseq);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                LowerGraphic (forceRedraw, gIDseq        );
            } finally {
                _releaseReply ($in);
            }
  } // LowerGraphic


  //i.e. change fillcolor to blus
  public void SetClientAttributes (boolean forceRedraw, com.bbn.openmap.corba.CSpecialist.UpdateRecord[] info)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("SetClientAttributes", false);
                $out.write_boolean (forceRedraw);
                com.bbn.openmap.corba.CSpecialist.GUpdateHelper.write ($out, info);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                SetClientAttributes (forceRedraw, info        );
            } finally {
                _releaseReply ($in);
            }
  } // SetClientAttributes


  //which means it doesn't do anything generally useful
  public void ping ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ping", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ping (        );
            } finally {
                _releaseReply ($in);
            }
  } // ping

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CSpecialist/GraphicChange:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GraphicChangeStub
