package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/_MapViewHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class _MapViewHolder implements org.omg.CORBA.portable.IDLEntity
{

  //This is not currently used for anything
  public com.bbn.openmap.corba.CSpecialist.LLPoint nwcorner = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint secorner = null;

  public _MapViewHolder ()
  {
  } // ctor

  public _MapViewHolder (com.bbn.openmap.corba.CSpecialist.LLPoint _nwcorner, com.bbn.openmap.corba.CSpecialist.LLPoint _secorner)
  {
    nwcorner = _nwcorner;
    secorner = _secorner;
  } // ctor

} // class _MapViewHolder
