package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/_ServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:47 PM EST
*/


//------------------------------------------------------------
public class _ServerStub extends org.omg.CORBA.portable.ObjectImpl implements com.bbn.openmap.corba.CSpecialist.Server
{


  // unique host:pid:layer context
  public com.bbn.openmap.corba.CSpecialist.UGraphic[] getRectangle (com.bbn.openmap.corba.CSpecialist.CProjection p, com.bbn.openmap.corba.CSpecialist.LLPoint ll1, com.bbn.openmap.corba.CSpecialist.LLPoint ll2, String staticArgs, org.omg.CORBA.StringHolder dynamicArgs, org.omg.CORBA.ShortHolder graphicSeletableDistance, org.omg.CORBA.BooleanHolder areaEvents, com.bbn.openmap.corba.CSpecialist.GraphicChange notifyOnChange, String uniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRectangle", true);
                com.bbn.openmap.corba.CSpecialist.CProjectionHelper.write ($out, p);
                com.bbn.openmap.corba.CSpecialist.LLPointHelper.write ($out, ll1);
                com.bbn.openmap.corba.CSpecialist.LLPointHelper.write ($out, ll2);
                $out.write_string (staticArgs);
                $out.write_string (dynamicArgs.value);
                com.bbn.openmap.corba.CSpecialist.GraphicChangeHelper.write ($out, notifyOnChange);
                $out.write_string (uniqueID);
                $in = _invoke ($out);
                com.bbn.openmap.corba.CSpecialist.UGraphic $result[] = com.bbn.openmap.corba.CSpecialist.UGraphicSeqHelper.read ($in);
                dynamicArgs.value = $in.read_string ();
                graphicSeletableDistance.value = $in.read_short ();
                areaEvents.value = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRectangle (p, ll1, ll2, staticArgs, dynamicArgs, graphicSeletableDistance, areaEvents, notifyOnChange, uniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // getRectangle

  public com.bbn.openmap.corba.CSpecialist.ActionUnion[] sendGesture (com.bbn.openmap.corba.CSpecialist.MouseEvent gesture, String uniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sendGesture", true);
                com.bbn.openmap.corba.CSpecialist.MouseEventHelper.write ($out, gesture);
                $out.write_string (uniqueID);
                $in = _invoke ($out);
                com.bbn.openmap.corba.CSpecialist.ActionUnion $result[] = com.bbn.openmap.corba.CSpecialist.ActionSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sendGesture (gesture, uniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // sendGesture


  // longer needed for context host:pid:layer
  public void signoff (String uniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("signoff", false);
                $out.write_string (uniqueID);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                signoff (uniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // signoff

  public com.bbn.openmap.corba.CSpecialist.UWidget[] getPaletteConfig (com.bbn.openmap.corba.CSpecialist.WidgetChange notifyOnChange, String staticArgs, org.omg.CORBA.StringHolder dynamicArgs, String uniqueID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPaletteConfig", true);
                com.bbn.openmap.corba.CSpecialist.WidgetChangeHelper.write ($out, notifyOnChange);
                $out.write_string (staticArgs);
                $out.write_string (dynamicArgs.value);
                $out.write_string (uniqueID);
                $in = _invoke ($out);
                com.bbn.openmap.corba.CSpecialist.UWidget $result[] = com.bbn.openmap.corba.CSpecialist.UWidgetSeqHelper.read ($in);
                dynamicArgs.value = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPaletteConfig (notifyOnChange, staticArgs, dynamicArgs, uniqueID        );
            } finally {
                _releaseReply ($in);
            }
  } // getPaletteConfig

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CSpecialist/Server:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerStub
