package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/ButtonBoxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface ButtonBoxOperations 
{
  String label ();
  void label (String newLabel);
  String[] buttons ();
  void buttons (String[] newButtons);
  void pressed (String box_label, String button_pressed, String uniqueID);
} // interface ButtonBoxOperations
