package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/ButtonBoxPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public abstract class ButtonBoxPOA extends org.omg.PortableServer.Servant
 implements com.bbn.openmap.corba.CSpecialist.ButtonBoxOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_label", new java.lang.Integer (0));
    _methods.put ("_set_label", new java.lang.Integer (1));
    _methods.put ("_get_buttons", new java.lang.Integer (2));
    _methods.put ("_set_buttons", new java.lang.Integer (3));
    _methods.put ("pressed", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CSpecialist/ButtonBox/_get_label
       {
         String $result = null;
         $result = this.label ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CSpecialist/ButtonBox/_set_label
       {
         String newLabel = in.read_string ();
         this.label (newLabel);
         out = $rh.createReply();
         break;
       }

       case 2:  // CSpecialist/ButtonBox/_get_buttons
       {
         String $result[] = null;
         $result = this.buttons ();
         out = $rh.createReply();
         com.bbn.openmap.corba.CSpecialist.stringsHelper.write (out, $result);
         break;
       }

       case 3:  // CSpecialist/ButtonBox/_set_buttons
       {
         String newButtons[] = com.bbn.openmap.corba.CSpecialist.stringsHelper.read (in);
         this.buttons (newButtons);
         out = $rh.createReply();
         break;
       }

       case 4:  // CSpecialist/ButtonBox/pressed
       {
         String box_label = in.read_string ();
         String button_pressed = in.read_string ();
         String uniqueID = in.read_string ();
         this.pressed (box_label, button_pressed, uniqueID);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CSpecialist/ButtonBox:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ButtonBox _this() 
  {
    return ButtonBoxHelper.narrow(
    super._this_object());
  }

  public ButtonBox _this(org.omg.CORBA.ORB orb) 
  {
    return ButtonBoxHelper.narrow(
    super._this_object(orb));
  }


} // class ButtonBoxPOA
