package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CColorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public interface CColorOperations 
{
  short red ();
  void red (short newRed);
  short green ();
  void green (short newGreen);
  short blue ();
  void blue (short newBlue);
  com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor fill ();
} // interface CColorOperations
