package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CheckBoxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface CheckBoxOperations 
{
  String label ();
  void label (String newLabel);
  com.bbn.openmap.corba.CSpecialist.CheckButton[] buttons ();
  void buttons (com.bbn.openmap.corba.CSpecialist.CheckButton[] newButtons);
  void selected (String box_label, com.bbn.openmap.corba.CSpecialist.CheckButton button, String uniqueID);
} // interface CheckBoxOperations
