package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CircleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface CircleOperations  extends com.bbn.openmap.corba.CSpecialist.GraphicOperations
{
  com.bbn.openmap.corba.CSpecialist.XYPoint p1 ();
  void p1 (com.bbn.openmap.corba.CSpecialist.XYPoint newP1);
  com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ();
  void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl1);
  float major ();
  void major (float newMajor);
  float minor ();
  void minor (float newMinor);
  short width ();
  void width (short newWidth);
  short height ();
  void height (short newHeight);
  com.bbn.openmap.corba.CSpecialist.CirclePackage.ECircle fill ();
} // interface CircleOperations
