package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CompOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/


// ----------------------------------------------------------------------
public interface CompOperations 
{
  com.bbn.openmap.corba.CSpecialist.ActionUnion[] sendGesture (com.bbn.openmap.corba.CSpecialist.MouseEvent gesture, String uniqueID);
  String cID ();
  com.bbn.openmap.corba.CSpecialist.EComp fill ();
} // interface CompOperations
