package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CProjection.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class CProjection implements org.omg.CORBA.portable.IDLEntity
{
  public short kind = (short)0;

  // ProjType (PT_Mercator...)
  public com.bbn.openmap.corba.CSpecialist.LLPoint center = null;
  public short height = (short)0;
  public short width = (short)0;
  public int scale = (int)0;

  public CProjection ()
  {
  } // ctor

  public CProjection (short _kind, com.bbn.openmap.corba.CSpecialist.LLPoint _center, short _height, short _width, int _scale)
  {
    kind = _kind;
    center = _center;
    height = _height;
    width = _width;
    scale = _scale;
  } // ctor

} // class CProjection
