package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CStippleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public interface CStippleOperations 
{
  short height ();
  short width ();
  byte[] data ();
  com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple fill ();
} // interface CStippleOperations
