package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/CTEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class CTEntry implements org.omg.CORBA.portable.IDLEntity
{
  public short red = (short)0;
  public short green = (short)0;
  public short blue = (short)0;
  public short open = (short)0;

  public CTEntry ()
  {
  } // ctor

  public CTEntry (short _red, short _green, short _blue, short _open)
  {
    red = _red;
    green = _green;
    blue = _blue;
    open = _open;
  } // ctor

} // class CTEntry
