package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/EComp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class EComp implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.Comp comp = null;
  public String cID = null;

  public EComp ()
  {
  } // ctor

  public EComp (com.bbn.openmap.corba.CSpecialist.Comp _comp, String _cID)
  {
    comp = _comp;
    cID = _cID;
  } // ctor

} // class EComp
