package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/ForceArrowOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface ForceArrowOperations  extends com.bbn.openmap.corba.CSpecialist.GraphicOperations
{
  com.bbn.openmap.corba.CSpecialist.XYPoint p1 ();
  void p1 (com.bbn.openmap.corba.CSpecialist.XYPoint newP1);
  com.bbn.openmap.corba.CSpecialist.XYPoint p2 ();
  void p2 (com.bbn.openmap.corba.CSpecialist.XYPoint newP2);
  com.bbn.openmap.corba.CSpecialist.XYPoint p3 ();
  void p3 (com.bbn.openmap.corba.CSpecialist.XYPoint newP3);
  com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ();
  void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl1);
  com.bbn.openmap.corba.CSpecialist.LLPoint ll2 ();
  void ll2 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl2);
  com.bbn.openmap.corba.CSpecialist.LLPoint ll3 ();
  void ll3 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl3);
  com.bbn.openmap.corba.CSpecialist.LLPoint offset ();
  void offset (com.bbn.openmap.corba.CSpecialist.LLPoint newOffset);
  com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrow fill ();
} // interface ForceArrowOperations
