package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/GraphicOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public interface GraphicOperations 
{

  //  original spot
  String gID ();
  com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType gType ();
  com.bbn.openmap.corba.CSpecialist.Comp obj ();
  void obj (com.bbn.openmap.corba.CSpecialist.Comp newObj);
  com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType lType ();
  void lType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType newLType);
  com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType rType ();
  void rType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType newRType);
  com.bbn.openmap.corba.CSpecialist.CColor color ();
  void color (com.bbn.openmap.corba.CSpecialist.CColor newColor);
  com.bbn.openmap.corba.CSpecialist.CColor fillColor ();
  void fillColor (com.bbn.openmap.corba.CSpecialist.CColor newFillColor);
  short lineWidth ();
  void lineWidth (short newLineWidth);
  com.bbn.openmap.corba.CSpecialist.CStipple stipple ();
  void stipple (com.bbn.openmap.corba.CSpecialist.CStipple newStipple);
  com.bbn.openmap.corba.CSpecialist.CStipple fillStipple ();
  void fillStipple (com.bbn.openmap.corba.CSpecialist.CStipple newFillStipple);
  com.bbn.openmap.corba.CSpecialist.GraphicPackage.DeclutterType dcType ();
  void dcType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.DeclutterType newDcType);
  com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic gfill ();
} // interface GraphicOperations
