package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/GraphicChangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:47 PM EST
*/


// ----------------------------------------------------------------------
public interface GraphicChangeOperations 
{

  //gives the mattserver a list of graphics that it needs to refetch
  void ChangeNotify (boolean forceRedraw, String[] gIDseq);

  //when it redraws, to do a new fillrectangle call)
  void ForgetAll (boolean forceRedraw);

  //changes the ordering of graphics
  void RaiseGraphic (boolean forceRedraw, String[] gIDseq);
  void LowerGraphic (boolean forceRedraw, String[] gIDseq);

  //i.e. change fillcolor to blus
  void SetClientAttributes (boolean forceRedraw, com.bbn.openmap.corba.CSpecialist.UpdateRecord[] info);

  //which means it doesn't do anything generally useful
  void ping ();
} // interface GraphicChangeOperations
