package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/InfoCompPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public abstract class InfoCompPOA extends org.omg.PortableServer.Servant
 implements com.bbn.openmap.corba.CSpecialist.InfoCompOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_info", new java.lang.Integer (0));
    _methods.put ("_get_iurl", new java.lang.Integer (1));
    _methods.put ("_get_ptext", new java.lang.Integer (2));
    _methods.put ("_get_htext", new java.lang.Integer (3));
    _methods.put ("sendGesture", new java.lang.Integer (4));
    _methods.put ("_get_cID", new java.lang.Integer (5));
    _methods.put ("fill", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CSpecialist/InfoComp/_get_info
       {
         String $result = null;
         $result = this.info ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // CSpecialist/InfoComp/_get_iurl
       {
         String $result = null;
         $result = this.iurl ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // CSpecialist/InfoComp/_get_ptext
       {
         String $result = null;
         $result = this.ptext ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // CSpecialist/InfoComp/_get_htext
       {
         String $result = null;
         $result = this.htext ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // CSpecialist/Comp/sendGesture
       {
         com.bbn.openmap.corba.CSpecialist.MouseEvent gesture = com.bbn.openmap.corba.CSpecialist.MouseEventHelper.read (in);
         String uniqueID = in.read_string ();
         com.bbn.openmap.corba.CSpecialist.ActionUnion $result[] = null;
         $result = this.sendGesture (gesture, uniqueID);
         out = $rh.createReply();
         com.bbn.openmap.corba.CSpecialist.ActionSeqHelper.write (out, $result);
         break;
       }

       case 5:  // CSpecialist/Comp/_get_cID
       {
         String $result = null;
         $result = this.cID ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // CSpecialist/Comp/fill
       {
         com.bbn.openmap.corba.CSpecialist.EComp $result = null;
         $result = this.fill ();
         out = $rh.createReply();
         com.bbn.openmap.corba.CSpecialist.ECompHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CSpecialist/InfoComp:1.0", 
    "IDL:CSpecialist/Comp:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public InfoComp _this() 
  {
    return InfoCompHelper.narrow(
    super._this_object());
  }

  public InfoComp _this(org.omg.CORBA.ORB orb) 
  {
    return InfoCompHelper.narrow(
    super._this_object(orb));
  }


} // class InfoCompPOA
