package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/InfoCompOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface InfoCompOperations  extends com.bbn.openmap.corba.CSpecialist.CompOperations
{
  String info ();
  String iurl ();
  String ptext ();
  String htext ();
} // interface InfoCompOperations
