package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/InfoComp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface InfoComp extends InfoCompOperations, com.bbn.openmap.corba.CSpecialist.Comp, org.omg.CORBA.portable.IDLEntity 
{
} // interface InfoComp
