package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/key_modifiers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class key_modifiers implements org.omg.CORBA.portable.IDLEntity
{
  public boolean alt = false;
  public boolean shift = false;
  public boolean control = false;

  public key_modifiers ()
  {
  } // ctor

  public key_modifiers (boolean _alt, boolean _shift, boolean _control)
  {
    alt = _alt;
    shift = _shift;
    control = _control;
  } // ctor

} // class key_modifiers
