package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/MouseEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class MouseEvent implements org.omg.CORBA.portable.IDLEntity
{
  private com.bbn.openmap.corba.CSpecialist.Mouse ___click;
  private com.bbn.openmap.corba.CSpecialist.Mouse ___motion;
  private com.bbn.openmap.corba.CSpecialist.Keypress ___keypress;
  private com.bbn.openmap.corba.CSpecialist._MapViewHolder ___mapviewchange;
  private com.bbn.openmap.corba.CSpecialist.MouseType __discriminator;
  private boolean __uninitialized = true;

  public MouseEvent ()
  {
  }

  public com.bbn.openmap.corba.CSpecialist.MouseType discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public com.bbn.openmap.corba.CSpecialist.Mouse click ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyclick (__discriminator);
    return ___click;
  }

  public void click (com.bbn.openmap.corba.CSpecialist.Mouse value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.MouseType.ClickEvent;
    ___click = value;
    __uninitialized = false;
  }

  public void click (com.bbn.openmap.corba.CSpecialist.MouseType discriminator, com.bbn.openmap.corba.CSpecialist.Mouse value)
  {
    verifyclick (discriminator);
    __discriminator = discriminator;
    ___click = value;
    __uninitialized = false;
  }

  private void verifyclick (com.bbn.openmap.corba.CSpecialist.MouseType discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.MouseType.ClickEvent)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.Mouse motion ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifymotion (__discriminator);
    return ___motion;
  }

  public void motion (com.bbn.openmap.corba.CSpecialist.Mouse value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.MouseType.MotionEvent;
    ___motion = value;
    __uninitialized = false;
  }

  public void motion (com.bbn.openmap.corba.CSpecialist.MouseType discriminator, com.bbn.openmap.corba.CSpecialist.Mouse value)
  {
    verifymotion (discriminator);
    __discriminator = discriminator;
    ___motion = value;
    __uninitialized = false;
  }

  private void verifymotion (com.bbn.openmap.corba.CSpecialist.MouseType discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.MouseType.MotionEvent)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.Keypress keypress ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifykeypress (__discriminator);
    return ___keypress;
  }

  public void keypress (com.bbn.openmap.corba.CSpecialist.Keypress value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.MouseType.KeyEvent;
    ___keypress = value;
    __uninitialized = false;
  }

  public void keypress (com.bbn.openmap.corba.CSpecialist.MouseType discriminator, com.bbn.openmap.corba.CSpecialist.Keypress value)
  {
    verifykeypress (discriminator);
    __discriminator = discriminator;
    ___keypress = value;
    __uninitialized = false;
  }

  private void verifykeypress (com.bbn.openmap.corba.CSpecialist.MouseType discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.MouseType.KeyEvent)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist._MapViewHolder mapviewchange ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifymapviewchange (__discriminator);
    return ___mapviewchange;
  }

  public void mapviewchange (com.bbn.openmap.corba.CSpecialist._MapViewHolder value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.MouseType.MapViewChangeEvent;
    ___mapviewchange = value;
    __uninitialized = false;
  }

  public void mapviewchange (com.bbn.openmap.corba.CSpecialist.MouseType discriminator, com.bbn.openmap.corba.CSpecialist._MapViewHolder value)
  {
    verifymapviewchange (discriminator);
    __discriminator = discriminator;
    ___mapviewchange = value;
    __uninitialized = false;
  }

  private void verifymapviewchange (com.bbn.openmap.corba.CSpecialist.MouseType discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.MouseType.MapViewChangeEvent)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class MouseEvent
