package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/PolyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface PolyOperations  extends com.bbn.openmap.corba.CSpecialist.GraphicOperations
{
  com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ();
  void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl1);
  com.bbn.openmap.corba.CSpecialist.PolyPackage.CoordMode cMode ();
  void cMode (com.bbn.openmap.corba.CSpecialist.PolyPackage.CoordMode newCMode);
  com.bbn.openmap.corba.CSpecialist.XYPoint[] xypoints ();
  void xypoints (com.bbn.openmap.corba.CSpecialist.XYPoint[] newXypoints);
  com.bbn.openmap.corba.CSpecialist.LLPoint[] llpoints ();
  void llpoints (com.bbn.openmap.corba.CSpecialist.LLPoint[] newLlpoints);
  com.bbn.openmap.corba.CSpecialist.PolyPackage.EPoly fill ();
} // interface PolyOperations
