package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/RadioBoxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface RadioBoxOperations 
{
  String label ();
  void label (String newLabel);
  String[] buttons ();
  void buttons (String[] newButtons);
  String selected_button ();
  void selected_button (String newSelected_button);
  void selected (String box_label, String selected_button, String uniqueID);
} // interface RadioBoxOperations
