package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/RasterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface RasterOperations  extends com.bbn.openmap.corba.CSpecialist.GraphicOperations
{
  com.bbn.openmap.corba.CSpecialist.XYPoint p1 ();
  void p1 (com.bbn.openmap.corba.CSpecialist.XYPoint newP1);
  com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ();
  void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint newLl1);
  byte[] pixels ();
  void pixels (byte[] newPixels);
  short width ();
  void width (short newWidth);
  short height ();
  void height (short newHeight);
  short x_hot ();
  void x_hot (short newX_hot);
  short y_hot ();
  void y_hot (short newY_hot);
  short colorsTotal ();
  void colorsTotal (short newColorsTotal);
  com.bbn.openmap.corba.CSpecialist.CTEntry[] ct ();
  void ct (com.bbn.openmap.corba.CSpecialist.CTEntry[] newCt);
  short transparent ();
  void transparent (short newTransparent);
  com.bbn.openmap.corba.CSpecialist.RasterPackage.ERaster fill ();
} // interface RasterOperations
