package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/ReorderType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public class ReorderType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static com.bbn.openmap.corba.CSpecialist.ReorderType[] __array = new com.bbn.openmap.corba.CSpecialist.ReorderType [__size];

  public static final int _RT_Raise = 0;
  public static final com.bbn.openmap.corba.CSpecialist.ReorderType RT_Raise = new com.bbn.openmap.corba.CSpecialist.ReorderType(_RT_Raise);
  public static final int _RT_Lower = 1;
  public static final com.bbn.openmap.corba.CSpecialist.ReorderType RT_Lower = new com.bbn.openmap.corba.CSpecialist.ReorderType(_RT_Lower);
  public static final int _RT_Delete = 2;
  public static final com.bbn.openmap.corba.CSpecialist.ReorderType RT_Delete = new com.bbn.openmap.corba.CSpecialist.ReorderType(_RT_Delete);

  public int value ()
  {
    return __value;
  }

  public static com.bbn.openmap.corba.CSpecialist.ReorderType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ReorderType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ReorderType
