package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/Revision.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public interface Revision
{

  // ----------------------------------------------------------------------
  public static final String value = "@(#)$Header: /cvs/distapps/openmap/src/corba/com/bbn/openmap/layer/specialist/Specialist.idl,v 1.2 2003/05/07 20:56:59 dietrick Exp $";
}
