package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:47 PM EST
*/


//------------------------------------------------------------
public interface ServerOperations 
{

  // unique host:pid:layer context
  com.bbn.openmap.corba.CSpecialist.UGraphic[] getRectangle (com.bbn.openmap.corba.CSpecialist.CProjection p, com.bbn.openmap.corba.CSpecialist.LLPoint ll1, com.bbn.openmap.corba.CSpecialist.LLPoint ll2, String staticArgs, org.omg.CORBA.StringHolder dynamicArgs, org.omg.CORBA.ShortHolder graphicSeletableDistance, org.omg.CORBA.BooleanHolder areaEvents, com.bbn.openmap.corba.CSpecialist.GraphicChange notifyOnChange, String uniqueID);
  com.bbn.openmap.corba.CSpecialist.ActionUnion[] sendGesture (com.bbn.openmap.corba.CSpecialist.MouseEvent gesture, String uniqueID);

  // longer needed for context host:pid:layer
  void signoff (String uniqueID);
  com.bbn.openmap.corba.CSpecialist.UWidget[] getPaletteConfig (com.bbn.openmap.corba.CSpecialist.WidgetChange notifyOnChange, String staticArgs, org.omg.CORBA.StringHolder dynamicArgs, String uniqueID);
} // interface ServerOperations
