package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/SliderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface SliderOperations 
{
  String label ();
  void label (String newLabel);
  short start ();
  void start (short newStart);
  short end ();
  void end (short newEnd);
  short value ();
  void value (short newValue);

  //initial position, between start and end
  boolean vertical ();

  //initial position, between start and end
  void vertical (boolean newVertical);
  void set (String label, short new_setting, String uniqueID);
} // interface SliderOperations
