package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/TextBoxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public interface TextBoxOperations 
{
  String label ();
  void label (String newLabel);
  String contents ();
  void contents (String newContents);
  void pressed (String box_label, String new_contents, String uniqueID);
} // interface TextBoxOperations
