package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/UGraphicHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

abstract public class UGraphicHelper
{
  private static String  _id = "IDL:CSpecialist/UGraphic:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.UGraphic that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.UGraphic extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [10];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for ebit (case label GT_Bitmap)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Bitmap);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "ebit",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for etext (case label GT_Text)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Text);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "etext",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for epoly (case label GT_Poly)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Poly);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.PolyPackage.EPolyHelper.type ();
      _members0[2] = new org.omg.CORBA.UnionMember (
        "epoly",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for eline (case label GT_Line)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Line);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.LinePackage.ELineHelper.type ();
      _members0[3] = new org.omg.CORBA.UnionMember (
        "eline",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for eunit (case label GT_UnitSymbol)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_UnitSymbol);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.EUnitSymbolHelper.type ();
      _members0[4] = new org.omg.CORBA.UnionMember (
        "eunit",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for e2525 (case label GT_2525Symbol)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_2525Symbol);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.E2525SymbolHelper.type ();
      _members0[5] = new org.omg.CORBA.UnionMember (
        "e2525",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for erect (case label GT_Rectangle)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Rectangle);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangleHelper.type ();
      _members0[6] = new org.omg.CORBA.UnionMember (
        "erect",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for ecirc (case label GT_Circle)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Circle);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.CirclePackage.ECircleHelper.type ();
      _members0[7] = new org.omg.CORBA.UnionMember (
        "ecirc",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for eras (case label GT_Raster)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_Raster);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.RasterPackage.ERasterHelper.type ();
      _members0[8] = new org.omg.CORBA.UnionMember (
        "eras",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for efarrow (case label GT_ForceArrow)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType.GT_ForceArrow);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.type ();
      _members0[9] = new org.omg.CORBA.UnionMember (
        "efarrow",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (com.bbn.openmap.corba.CSpecialist.UGraphicHelper.id (), "UGraphic", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.UGraphic read (org.omg.CORBA.portable.InputStream istream)
  {
    com.bbn.openmap.corba.CSpecialist.UGraphic value = new com.bbn.openmap.corba.CSpecialist.UGraphic ();
    com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType _dis0 = null;
    _dis0 = com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.read (istream);
    switch (_dis0.value ())
    {
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Bitmap:
        com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmap _ebit = null;
        _ebit = com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.read (istream);
        value.ebit (_ebit);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Text:
        com.bbn.openmap.corba.CSpecialist.TextPackage.EText _etext = null;
        _etext = com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.read (istream);
        value.etext (_etext);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Poly:
        com.bbn.openmap.corba.CSpecialist.PolyPackage.EPoly _epoly = null;
        _epoly = com.bbn.openmap.corba.CSpecialist.PolyPackage.EPolyHelper.read (istream);
        value.epoly (_epoly);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Line:
        com.bbn.openmap.corba.CSpecialist.LinePackage.ELine _eline = null;
        _eline = com.bbn.openmap.corba.CSpecialist.LinePackage.ELineHelper.read (istream);
        value.eline (_eline);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_UnitSymbol:
        com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.EUnitSymbol _eunit = null;
        _eunit = com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.EUnitSymbolHelper.read (istream);
        value.eunit (_eunit);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_2525Symbol:
        com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.E2525Symbol _e2525 = null;
        _e2525 = com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.E2525SymbolHelper.read (istream);
        value.e2525 (_e2525);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Rectangle:
        com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangle _erect = null;
        _erect = com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangleHelper.read (istream);
        value.erect (_erect);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Circle:
        com.bbn.openmap.corba.CSpecialist.CirclePackage.ECircle _ecirc = null;
        _ecirc = com.bbn.openmap.corba.CSpecialist.CirclePackage.ECircleHelper.read (istream);
        value.ecirc (_ecirc);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Raster:
        com.bbn.openmap.corba.CSpecialist.RasterPackage.ERaster _eras = null;
        _eras = com.bbn.openmap.corba.CSpecialist.RasterPackage.ERasterHelper.read (istream);
        value.eras (_eras);
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_ForceArrow:
        com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrow _efarrow = null;
        _efarrow = com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.read (istream);
        value.efarrow (_efarrow);
        break;
      default:
        value._default( _dis0 ) ;
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.UGraphic value)
  {
    com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicTypeHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Bitmap:
        com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.write (ostream, value.ebit ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Text:
        com.bbn.openmap.corba.CSpecialist.TextPackage.ETextHelper.write (ostream, value.etext ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Poly:
        com.bbn.openmap.corba.CSpecialist.PolyPackage.EPolyHelper.write (ostream, value.epoly ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Line:
        com.bbn.openmap.corba.CSpecialist.LinePackage.ELineHelper.write (ostream, value.eline ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_UnitSymbol:
        com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.EUnitSymbolHelper.write (ostream, value.eunit ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_2525Symbol:
        com.bbn.openmap.corba.CSpecialist.U2525SymbolPackage.E2525SymbolHelper.write (ostream, value.e2525 ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Rectangle:
        com.bbn.openmap.corba.CSpecialist.RectanglePackage.ERectangleHelper.write (ostream, value.erect ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Circle:
        com.bbn.openmap.corba.CSpecialist.CirclePackage.ECircleHelper.write (ostream, value.ecirc ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_Raster:
        com.bbn.openmap.corba.CSpecialist.RasterPackage.ERasterHelper.write (ostream, value.eras ());
        break;
      case com.bbn.openmap.corba.CSpecialist.GraphicPackage.GraphicType._GT_ForceArrow:
        com.bbn.openmap.corba.CSpecialist.ForceArrowPackage.EForceArrowHelper.write (ostream, value.efarrow ());
        break;
    }
  }

}
