package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/UpdateRecord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class UpdateRecord implements org.omg.CORBA.portable.IDLEntity
{
  public String gID = null;
  public com.bbn.openmap.corba.CSpecialist.UpdateGraphic objectUpdates[] = null;

  public UpdateRecord ()
  {
  } // ctor

  public UpdateRecord (String _gID, com.bbn.openmap.corba.CSpecialist.UpdateGraphic[] _objectUpdates)
  {
    gID = _gID;
    objectUpdates = _objectUpdates;
  } // ctor

} // class UpdateRecord
