package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/UWidgetHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

abstract public class UWidgetHelper
{
  private static String  _id = "IDL:CSpecialist/UWidget:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.UWidget that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.UWidget extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [6];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for cb (case label WT_CheckBox)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_CheckBox);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.CheckBoxHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "cb",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for rb (case label WT_RadioBox)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_RadioBox);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.RadioBoxHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "rb",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for slide (case label WT_Slider)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_Slider);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.SliderHelper.type ();
      _members0[2] = new org.omg.CORBA.UnionMember (
        "slide",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for bb (case label WT_ButtonBox)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_ButtonBox);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.ButtonBoxHelper.type ();
      _members0[3] = new org.omg.CORBA.UnionMember (
        "bb",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for lb (case label WT_ListBox)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_ListBox);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.ListBoxHelper.type ();
      _members0[4] = new org.omg.CORBA.UnionMember (
        "lb",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for tb (case label WT_TextBox)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.WidgetType.WT_TextBox);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.TextBoxHelper.type ();
      _members0[5] = new org.omg.CORBA.UnionMember (
        "tb",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (com.bbn.openmap.corba.CSpecialist.UWidgetHelper.id (), "UWidget", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.UWidget read (org.omg.CORBA.portable.InputStream istream)
  {
    com.bbn.openmap.corba.CSpecialist.UWidget value = new com.bbn.openmap.corba.CSpecialist.UWidget ();
    com.bbn.openmap.corba.CSpecialist.WidgetType _dis0 = null;
    _dis0 = com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.read (istream);
    switch (_dis0.value ())
    {
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_CheckBox:
        com.bbn.openmap.corba.CSpecialist.CheckBox _cb = null;
        _cb = com.bbn.openmap.corba.CSpecialist.CheckBoxHelper.read (istream);
        value.cb (_cb);
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_RadioBox:
        com.bbn.openmap.corba.CSpecialist.RadioBox _rb = null;
        _rb = com.bbn.openmap.corba.CSpecialist.RadioBoxHelper.read (istream);
        value.rb (_rb);
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_Slider:
        com.bbn.openmap.corba.CSpecialist.Slider _slide = null;
        _slide = com.bbn.openmap.corba.CSpecialist.SliderHelper.read (istream);
        value.slide (_slide);
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_ButtonBox:
        com.bbn.openmap.corba.CSpecialist.ButtonBox _bb = null;
        _bb = com.bbn.openmap.corba.CSpecialist.ButtonBoxHelper.read (istream);
        value.bb (_bb);
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_ListBox:
        com.bbn.openmap.corba.CSpecialist.ListBox _lb = null;
        _lb = com.bbn.openmap.corba.CSpecialist.ListBoxHelper.read (istream);
        value.lb (_lb);
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_TextBox:
        com.bbn.openmap.corba.CSpecialist.TextBox _tb = null;
        _tb = com.bbn.openmap.corba.CSpecialist.TextBoxHelper.read (istream);
        value.tb (_tb);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.UWidget value)
  {
    com.bbn.openmap.corba.CSpecialist.WidgetTypeHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_CheckBox:
        com.bbn.openmap.corba.CSpecialist.CheckBoxHelper.write (ostream, value.cb ());
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_RadioBox:
        com.bbn.openmap.corba.CSpecialist.RadioBoxHelper.write (ostream, value.rb ());
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_Slider:
        com.bbn.openmap.corba.CSpecialist.SliderHelper.write (ostream, value.slide ());
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_ButtonBox:
        com.bbn.openmap.corba.CSpecialist.ButtonBoxHelper.write (ostream, value.bb ());
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_ListBox:
        com.bbn.openmap.corba.CSpecialist.ListBoxHelper.write (ostream, value.lb ());
        break;
      case com.bbn.openmap.corba.CSpecialist.WidgetType._WT_TextBox:
        com.bbn.openmap.corba.CSpecialist.TextBoxHelper.write (ostream, value.tb ());
        break;
    }
  }

}
