package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/WidgetChangeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:47 PM EST
*/

public interface WidgetChangeOperations 
{

  //it will do a new getPaletteConfig() call)
  void ForgetAll (boolean forceRedo);
} // interface WidgetChangeOperations
