package com.bbn.openmap.corba.CSpecialist;


/**
* com/bbn/openmap/corba/CSpecialist/XYPoint.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class XYPoint implements org.omg.CORBA.portable.IDLEntity
{
  public short x = (short)0;
  public short y = (short)0;

  public XYPoint ()
  {
  } // ctor

  public XYPoint (short _x, short _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class XYPoint
