package com.bbn.openmap.corba.CSpecialist.BitmapPackage;


/**
* com/bbn/openmap/corba/CSpecialist/BitmapPackage/BF_updateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

abstract public class BF_updateHelper
{
  private static String  _id = "IDL:CSpecialist/Bitmap/BF_update:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [8];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for p1 (case label BF_p1)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_p1);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "p1",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for ll1 (case label BF_ll1)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_ll1);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "ll1",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for width (case label BF_width)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_width);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
      _members0[2] = new org.omg.CORBA.UnionMember (
        "width",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for height (case label BF_height)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_height);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
      _members0[3] = new org.omg.CORBA.UnionMember (
        "height",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for x_hot (case label BF_x_hot)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_x_hot);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
      _members0[4] = new org.omg.CORBA.UnionMember (
        "x_hot",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for y_hot (case label BF_y_hot)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_y_hot);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
      _members0[5] = new org.omg.CORBA.UnionMember (
        "y_hot",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for bits (case label BF_bits)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bits);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
      _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.bbn.openmap.corba.CSpecialist.binarydataHelper.id (), "binarydata", _tcOf_members0);
      _members0[6] = new org.omg.CORBA.UnionMember (
        "bits",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for bmref (case label BF_bmref)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.insert (_anyOf_members0, com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bmref);
      _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.CStippleHelper.type ();
      _members0[7] = new org.omg.CORBA.UnionMember (
        "bmref",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_updateHelper.id (), "BF_update", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update read (org.omg.CORBA.portable.InputStream istream)
  {
    com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update value = new com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update ();
    com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields _dis0 = null;
    _dis0 = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.read (istream);
    switch (_dis0.value ())
    {
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_p1:
        com.bbn.openmap.corba.CSpecialist.XYPoint _p1 = null;
        _p1 = com.bbn.openmap.corba.CSpecialist.XYPointHelper.read (istream);
        value.p1 (_p1);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_ll1:
        com.bbn.openmap.corba.CSpecialist.LLPoint _ll1 = null;
        _ll1 = com.bbn.openmap.corba.CSpecialist.LLPointHelper.read (istream);
        value.ll1 (_ll1);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_width:
        short _width = (short)0;
        _width = istream.read_ushort ();
        value.width (_width);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_height:
        short _height = (short)0;
        _height = istream.read_ushort ();
        value.height (_height);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_x_hot:
        short _x_hot = (short)0;
        _x_hot = istream.read_ushort ();
        value.x_hot (_x_hot);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_y_hot:
        short _y_hot = (short)0;
        _y_hot = istream.read_ushort ();
        value.y_hot (_y_hot);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_bits:
        byte _bits[] = null;
        _bits = com.bbn.openmap.corba.CSpecialist.binarydataHelper.read (istream);
        value.bits (_bits);
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_bmref:
        com.bbn.openmap.corba.CSpecialist.CStipple _bmref = null;
        _bmref = com.bbn.openmap.corba.CSpecialist.CStippleHelper.read (istream);
        value.bmref (_bmref);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.BitmapPackage.BF_update value)
  {
    com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFieldsHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_p1:
        com.bbn.openmap.corba.CSpecialist.XYPointHelper.write (ostream, value.p1 ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_ll1:
        com.bbn.openmap.corba.CSpecialist.LLPointHelper.write (ostream, value.ll1 ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_width:
        ostream.write_ushort (value.width ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_height:
        ostream.write_ushort (value.height ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_x_hot:
        ostream.write_ushort (value.x_hot ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_y_hot:
        ostream.write_ushort (value.y_hot ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_bits:
        com.bbn.openmap.corba.CSpecialist.binarydataHelper.write (ostream, value.bits ());
        break;
      case com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields._BF_bmref:
        com.bbn.openmap.corba.CSpecialist.CStippleHelper.write (ostream, value.bmref ());
        break;
    }
  }

}
