package com.bbn.openmap.corba.CSpecialist.BitmapPackage;


/**
* com/bbn/openmap/corba/CSpecialist/BitmapPackage/BF_update.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class BF_update implements org.omg.CORBA.portable.IDLEntity
{
  private com.bbn.openmap.corba.CSpecialist.XYPoint ___p1;
  private com.bbn.openmap.corba.CSpecialist.LLPoint ___ll1;
  private short ___width;
  private short ___height;
  private short ___x_hot;
  private short ___y_hot;
  private byte[] ___bits;
  private com.bbn.openmap.corba.CSpecialist.CStipple ___bmref;
  private com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields __discriminator;
  private boolean __uninitialized = true;

  public BF_update ()
  {
  }

  public com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyp1 (__discriminator);
    return ___p1;
  }

  public void p1 (com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_p1;
    ___p1 = value;
    __uninitialized = false;
  }

  public void p1 (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.XYPoint value)
  {
    verifyp1 (discriminator);
    __discriminator = discriminator;
    ___p1 = value;
    __uninitialized = false;
  }

  private void verifyp1 (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_p1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyll1 (__discriminator);
    return ___ll1;
  }

  public void ll1 (com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_ll1;
    ___ll1 = value;
    __uninitialized = false;
  }

  public void ll1 (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.LLPoint value)
  {
    verifyll1 (discriminator);
    __discriminator = discriminator;
    ___ll1 = value;
    __uninitialized = false;
  }

  private void verifyll1 (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_ll1)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short width ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifywidth (__discriminator);
    return ___width;
  }

  public void width (short value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_width;
    ___width = value;
    __uninitialized = false;
  }

  public void width (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, short value)
  {
    verifywidth (discriminator);
    __discriminator = discriminator;
    ___width = value;
    __uninitialized = false;
  }

  private void verifywidth (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_width)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short height ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyheight (__discriminator);
    return ___height;
  }

  public void height (short value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_height;
    ___height = value;
    __uninitialized = false;
  }

  public void height (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, short value)
  {
    verifyheight (discriminator);
    __discriminator = discriminator;
    ___height = value;
    __uninitialized = false;
  }

  private void verifyheight (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_height)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short x_hot ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyx_hot (__discriminator);
    return ___x_hot;
  }

  public void x_hot (short value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_x_hot;
    ___x_hot = value;
    __uninitialized = false;
  }

  public void x_hot (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, short value)
  {
    verifyx_hot (discriminator);
    __discriminator = discriminator;
    ___x_hot = value;
    __uninitialized = false;
  }

  private void verifyx_hot (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_x_hot)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short y_hot ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyy_hot (__discriminator);
    return ___y_hot;
  }

  public void y_hot (short value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_y_hot;
    ___y_hot = value;
    __uninitialized = false;
  }

  public void y_hot (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, short value)
  {
    verifyy_hot (discriminator);
    __discriminator = discriminator;
    ___y_hot = value;
    __uninitialized = false;
  }

  private void verifyy_hot (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_y_hot)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public byte[] bits ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifybits (__discriminator);
    return ___bits;
  }

  public void bits (byte[] value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bits;
    ___bits = value;
    __uninitialized = false;
  }

  public void bits (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, byte[] value)
  {
    verifybits (discriminator);
    __discriminator = discriminator;
    ___bits = value;
    __uninitialized = false;
  }

  private void verifybits (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bits)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.CStipple bmref ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifybmref (__discriminator);
    return ___bmref;
  }

  public void bmref (com.bbn.openmap.corba.CSpecialist.CStipple value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bmref;
    ___bmref = value;
    __uninitialized = false;
  }

  public void bmref (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.CStipple value)
  {
    verifybmref (discriminator);
    __discriminator = discriminator;
    ___bmref = value;
    __uninitialized = false;
  }

  private void verifybmref (com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.BitmapPackage.settableFields.BF_bmref)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class BF_update
