package com.bbn.openmap.corba.CSpecialist.BitmapPackage;

/**
* com/bbn/openmap/corba/CSpecialist/BitmapPackage/EBitmapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class EBitmapHolder implements org.omg.CORBA.portable.Streamable
{
  public com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmap value = null;

  public EBitmapHolder ()
  {
  }

  public EBitmapHolder (com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmap initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.bbn.openmap.corba.CSpecialist.BitmapPackage.EBitmapHelper.type ();
  }

}
