package com.bbn.openmap.corba.CSpecialist.CirclePackage;


/**
* com/bbn/openmap/corba/CSpecialist/CirclePackage/ECircle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class ECircle implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic egraphic = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 = null;
  public float major = (float)0;
  public float minor = (float)0;
  public short width = (short)0;
  public short height = (short)0;

  public ECircle ()
  {
  } // ctor

  public ECircle (com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic _egraphic, com.bbn.openmap.corba.CSpecialist.XYPoint _p1, com.bbn.openmap.corba.CSpecialist.LLPoint _ll1, float _major, float _minor, short _width, short _height)
  {
    egraphic = _egraphic;
    p1 = _p1;
    ll1 = _ll1;
    major = _major;
    minor = _minor;
    width = _width;
    height = _height;
  } // ctor

} // class ECircle
