package com.bbn.openmap.plugin.corbaImage.corbaImageServer;


/**
* com/bbn/openmap/plugin/corbaImage/corbaImageServer/_ServerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/plugin/corbaImage/CorbaImageServer.idl
* Tuesday, November 12, 2013 11:07:48 PM EST
*/


//------------------------------------------------------------
public class _ServerStub extends org.omg.CORBA.portable.ObjectImpl implements com.bbn.openmap.plugin.corbaImage.corbaImageServer.Server
{

  public byte[] getImage (String request)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getImage", true);
                $out.write_string (request);
                $in = _invoke ($out);
                byte $result[] = com.bbn.openmap.plugin.corbaImage.corbaImageServer.DataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getImage (request        );
            } finally {
                _releaseReply ($in);
            }
  } // getImage

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corbaImageServer/Server:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ServerStub
