package com.bbn.openmap.plugin.corbaImage.corbaImageServer;


/**
* com/bbn/openmap/plugin/corbaImage/corbaImageServer/Revision.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/plugin/corbaImage/CorbaImageServer.idl
* Tuesday, November 12, 2013 11:07:48 PM EST
*/

public interface Revision
{

  // ----------------------------------------------------------------------
  public static final String value = "@(#)$Header: /cvs/distapps/openmap/src/corba/com/bbn/openmap/plugin/corbaImage/CorbaImageServer.idl,v 1.1.1.1 2003/02/14 21:35:47 dietrick Exp $";
}
