package com.bbn.openmap.plugin.corbaImage.corbaImageServer;


/**
* com/bbn/openmap/plugin/corbaImage/corbaImageServer/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/plugin/corbaImage/CorbaImageServer.idl
* Tuesday, November 12, 2013 11:07:48 PM EST
*/


//------------------------------------------------------------
public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Server
