package com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider;


/**
* com/bbn/openmap/layer/rpf/corba/CRpfFrameProvider/CRFPViewAttributes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/rpf/corba/CorbaRpfFrameProvider.idl
* Tuesday, November 12, 2013 11:07:44 PM EST
*/

public final class CRFPViewAttributes implements org.omg.CORBA.portable.IDLEntity
{
  public short numberOfColors = (short)0;
  public short opaqueness = (short)0;
  public boolean scaleImages = false;
  public float imageScaleFactor = (float)0;
  public String chartSeries = null;

  public CRFPViewAttributes ()
  {
  } // ctor

  public CRFPViewAttributes (short _numberOfColors, short _opaqueness, boolean _scaleImages, float _imageScaleFactor, String _chartSeries)
  {
    numberOfColors = _numberOfColors;
    opaqueness = _opaqueness;
    scaleImages = _scaleImages;
    imageScaleFactor = _imageScaleFactor;
    chartSeries = _chartSeries;
  } // ctor

} // class CRFPViewAttributes
