package com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider;


/**
* com/bbn/openmap/layer/rpf/corba/CRpfFrameProvider/ServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/rpf/corba/CorbaRpfFrameProvider.idl
* Tuesday, November 12, 2013 11:07:44 PM EST
*/


//------------------------------------------------------------
public interface ServerOperations 
{
  void setViewAttributes (com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.CRFPViewAttributes va, String uniqueID);
  com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.CRFPCoverageBox[] getCoverage (float ullat, float ullon, float lrlat, float lrlon, com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.CRFPCADRGProjection p, String uniqueID);
  com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.CRFPCoverageBox[] getCatalogCoverage (float ullat, float ullon, float lrlat, float lrlon, com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.CRFPCADRGProjection p, String chartSeriesCode, String uniqueID);
  byte[] getSubframeData (short tocNumber, short entryNumber, short x, short y, float jpegQuality, String uniqueID);
  com.bbn.openmap.layer.rpf.corba.CRpfFrameProvider.RawImage getRawSubframeData (short tocNumber, short entryNumber, short x, short y, String uniqueID);
  String getSubframeAttributes (short tocNumber, short entryNumber, short x, short y, String uniqueID);
  void signoff (String uniqueID);
} // interface ServerOperations
