package com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage;


/**
* com/bbn/openmap/corba/CSpecialist/UnitSymbolPackage/EUnitSymbol.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class EUnitSymbol implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic egraphic = null;
  public com.bbn.openmap.corba.CSpecialist.XYPoint p1 = null;
  public com.bbn.openmap.corba.CSpecialist.LLPoint ll1 = null;
  public String group = null;
  public String symbol = null;
  public String echelon = null;
  public String left1 = null;
  public String left2 = null;
  public String left3 = null;
  public String left4 = null;
  public String right1 = null;
  public String right2 = null;
  public String right3 = null;
  public String right4 = null;
  public String top1 = null;
  public String bottom1 = null;
  public short nom_size = (short)0;
  public short min_size = (short)0;
  public short max_size = (short)0;
  public int scale = (int)0;
  public boolean is_hq = false;
  public float rotate = (float)0;

  public EUnitSymbol ()
  {
  } // ctor

  public EUnitSymbol (com.bbn.openmap.corba.CSpecialist.GraphicPackage.EGraphic _egraphic, com.bbn.openmap.corba.CSpecialist.XYPoint _p1, com.bbn.openmap.corba.CSpecialist.LLPoint _ll1, String _group, String _symbol, String _echelon, String _left1, String _left2, String _left3, String _left4, String _right1, String _right2, String _right3, String _right4, String _top1, String _bottom1, short _nom_size, short _min_size, short _max_size, int _scale, boolean _is_hq, float _rotate)
  {
    egraphic = _egraphic;
    p1 = _p1;
    ll1 = _ll1;
    group = _group;
    symbol = _symbol;
    echelon = _echelon;
    left1 = _left1;
    left2 = _left2;
    left3 = _left3;
    left4 = _left4;
    right1 = _right1;
    right2 = _right2;
    right3 = _right3;
    right4 = _right4;
    top1 = _top1;
    bottom1 = _bottom1;
    nom_size = _nom_size;
    min_size = _min_size;
    max_size = _max_size;
    scale = _scale;
    is_hq = _is_hq;
    rotate = _rotate;
  } // ctor

} // class EUnitSymbol
