package com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage;


/**
* com/bbn/openmap/corba/CSpecialist/UnitSymbolPackage/settableFieldsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/


// rotate unit 0.0 -> 180.0 degrees
abstract public class settableFieldsHelper
{
  private static String  _id = "IDL:CSpecialist/UnitSymbol/settableFields:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFields that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFields extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFieldsHelper.id (), "settableFields", new String[] { "USF_p1", "USF_ll1", "USF_group", "USF_symbol", "USF_echelon", "USF_left1", "USF_left2", "USF_left3", "USF_left4", "USF_right1", "USF_right2", "USF_right3", "USF_right4", "USF_top1", "USF_bottom1", "USF_nom_size", "USF_min_size", "USF_max_size", "USF_scale", "USF_is_hq", "USF_rotate"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFields read (org.omg.CORBA.portable.InputStream istream)
  {
    return com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFields.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.UnitSymbolPackage.settableFields value)
  {
    ostream.write_long (value.value ());
  }

}
