package com.bbn.openmap.corba.CSpecialist.GraphicPackage;


/**
* com/bbn/openmap/corba/CSpecialist/GraphicPackage/GF_update.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:46 PM EST
*/

public final class GF_update implements org.omg.CORBA.portable.IDLEntity
{
  private com.bbn.openmap.corba.CSpecialist.EComp ___obj;
  private com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType ___lType;
  private com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType ___rType;
  private com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor ___color;
  private com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor ___fillColor;
  private short ___lineWidth;
  private com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple ___stipple;
  private com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple ___fillStipple;
  private com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields __discriminator;
  private boolean __uninitialized = true;

  public GF_update ()
  {
  }

  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public com.bbn.openmap.corba.CSpecialist.EComp obj ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyobj (__discriminator);
    return ___obj;
  }

  public void obj (com.bbn.openmap.corba.CSpecialist.EComp value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_object;
    ___obj = value;
    __uninitialized = false;
  }

  public void obj (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.EComp value)
  {
    verifyobj (discriminator);
    __discriminator = discriminator;
    ___obj = value;
    __uninitialized = false;
  }

  private void verifyobj (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_object)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType lType ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifylType (__discriminator);
    return ___lType;
  }

  public void lType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_lType;
    ___lType = value;
    __uninitialized = false;
  }

  public void lType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.GraphicPackage.LineType value)
  {
    verifylType (discriminator);
    __discriminator = discriminator;
    ___lType = value;
    __uninitialized = false;
  }

  private void verifylType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_lType)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType rType ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyrType (__discriminator);
    return ___rType;
  }

  public void rType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_rType;
    ___rType = value;
    __uninitialized = false;
  }

  public void rType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.GraphicPackage.RenderType value)
  {
    verifyrType (discriminator);
    __discriminator = discriminator;
    ___rType = value;
    __uninitialized = false;
  }

  private void verifyrType (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_rType)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor color ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifycolor (__discriminator);
    return ___color;
  }

  public void color (com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_color;
    ___color = value;
    __uninitialized = false;
  }

  public void color (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor value)
  {
    verifycolor (discriminator);
    __discriminator = discriminator;
    ___color = value;
    __uninitialized = false;
  }

  private void verifycolor (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_color)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor fillColor ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyfillColor (__discriminator);
    return ___fillColor;
  }

  public void fillColor (com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_fillColor;
    ___fillColor = value;
    __uninitialized = false;
  }

  public void fillColor (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.CColorPackage.EColor value)
  {
    verifyfillColor (discriminator);
    __discriminator = discriminator;
    ___fillColor = value;
    __uninitialized = false;
  }

  private void verifyfillColor (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_fillColor)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public short lineWidth ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifylineWidth (__discriminator);
    return ___lineWidth;
  }

  public void lineWidth (short value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_lineWidth;
    ___lineWidth = value;
    __uninitialized = false;
  }

  public void lineWidth (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, short value)
  {
    verifylineWidth (discriminator);
    __discriminator = discriminator;
    ___lineWidth = value;
    __uninitialized = false;
  }

  private void verifylineWidth (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_lineWidth)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple stipple ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifystipple (__discriminator);
    return ___stipple;
  }

  public void stipple (com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_stipple;
    ___stipple = value;
    __uninitialized = false;
  }

  public void stipple (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value)
  {
    verifystipple (discriminator);
    __discriminator = discriminator;
    ___stipple = value;
    __uninitialized = false;
  }

  private void verifystipple (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_stipple)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple fillStipple ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyfillStipple (__discriminator);
    return ___fillStipple;
  }

  public void fillStipple (com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value)
  {
    __discriminator = com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_fillStipple;
    ___fillStipple = value;
    __uninitialized = false;
  }

  public void fillStipple (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator, com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value)
  {
    verifyfillStipple (discriminator);
    __discriminator = discriminator;
    ___fillStipple = value;
    __uninitialized = false;
  }

  private void verifyfillStipple (com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields discriminator)
  {
    if (discriminator != com.bbn.openmap.corba.CSpecialist.GraphicPackage.settableFields.GF_fillStipple)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class GF_update
