package com.bbn.openmap.corba.CSpecialist.CStipplePackage;


/**
* com/bbn/openmap/corba/CSpecialist/CStipplePackage/EStipple.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

public final class EStipple implements org.omg.CORBA.portable.IDLEntity
{
  public com.bbn.openmap.corba.CSpecialist.CStipple stipple = null;
  public short height = (short)0;
  public short width = (short)0;
  public byte data[] = null;

  public EStipple ()
  {
  } // ctor

  public EStipple (com.bbn.openmap.corba.CSpecialist.CStipple _stipple, short _height, short _width, byte[] _data)
  {
    stipple = _stipple;
    height = _height;
    width = _width;
    data = _data;
  } // ctor

} // class EStipple
