package com.bbn.openmap.corba.CSpecialist.CStipplePackage;


/**
* com/bbn/openmap/corba/CSpecialist/CStipplePackage/EStippleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/corba/com/bbn/openmap/layer/specialist/Specialist.idl
* Tuesday, November 12, 2013 11:07:45 PM EST
*/

abstract public class EStippleHelper
{
  private static String  _id = "IDL:CSpecialist/CStipple/EStipple:1.0";

  public static void insert (org.omg.CORBA.Any a, com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = com.bbn.openmap.corba.CSpecialist.CStippleHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "stipple",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _members0[1] = new org.omg.CORBA.StructMember (
            "height",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ushort);
          _members0[2] = new org.omg.CORBA.StructMember (
            "width",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (com.bbn.openmap.corba.CSpecialist.binarydataHelper.id (), "binarydata", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "data",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStippleHelper.id (), "EStipple", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple read (org.omg.CORBA.portable.InputStream istream)
  {
    com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value = new com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple ();
    value.stipple = com.bbn.openmap.corba.CSpecialist.CStippleHelper.read (istream);
    value.height = istream.read_ushort ();
    value.width = istream.read_ushort ();
    value.data = com.bbn.openmap.corba.CSpecialist.binarydataHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.bbn.openmap.corba.CSpecialist.CStipplePackage.EStipple value)
  {
    com.bbn.openmap.corba.CSpecialist.CStippleHelper.write (ostream, value.stipple);
    ostream.write_ushort (value.height);
    ostream.write_ushort (value.width);
    com.bbn.openmap.corba.CSpecialist.binarydataHelper.write (ostream, value.data);
  }

}
